# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d436e9e3a0bcf0baec2816bc4ebb068feb76236df221c7dbd88036a4b6da7f3a1037d545029caa57e12c38b6cd544f66200d57ff43722839864b3b948b0db71b

test:
  secret_key_base: 2ea1a961aac834bb32897f870029c88fe9d0317f85b720de9c0ef1776601e334625ab22e68f42de98411bac22a6985dedfb76f630f58f99b9e4dcce22ed0a9f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
